setwd("/Users/ERubi/Desktop")
library(sqldf)
temp <- tempfile()
download.file("https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip",temp, mode ="wb")
unzip(temp)
fh<-file("household_power_consumption.txt","r")
hhpower<- read.csv.sql("household_power_consumption.txt", sql = "SELECT * FROM file WHERE Date='1/2/2007' OR Date='2/2/2007'", sep = ";", eol = "\n")
unlink(temp)
colnames(hhpower)<- c("Date","Time","Global_active_power","Global_reactive_power","Voltage","Global_intensity","Sub_metering_1","Sub_metering_2","Sub_metering_3" )
DateTime <-paste(hhpower$Date,hhpower$Time)
hhpower$DateTime <-strptime(DateTime, "%d/%m/%Y %H:%M:%S")

#Plot 4
par(mfrow=c(2,2), mar=c(5,5,2,2))
with (hhpower, {
        plot(DateTime,Global_active_power, type="l", ylab="Global Active Power",xlab="")
        plot(DateTime, Voltage, type="l",ylab="Voltage",xlab="datetime")
        plot(DateTime, Sub_metering_1,type="l",ylab="Energy sub metering",xlab="") 
        lines(DateTime, Sub_metering_2, col="red")
        lines(DateTime, Sub_metering_3, col="blue")
        legend ("topright", bty="n",lty=1, cex = 0.9, col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
        plot(DateTime, Global_reactive_power, type="l",xlab="datetime")
})
dev.copy(png, file="plot4.png", width = 480, height = 480)
dev.off()